#include QMK_KEYBOARD_H

/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
	[0] = LAYOUT_5x6(KC_GRV, KC_1, KC_2, KC_3, KC_4, KC_5, KC_6, KC_7, KC_8, KC_9, KC_0, KC_DEL, KC_TAB, KC_Q, KC_W, KC_E, KC_R, KC_T, KC_Y, KC_U, KC_I, KC_O, KC_P, KC_BSLS, KC_CAPS, KC_A, KC_S, KC_D, KC_F, KC_G, KC_H, KC_J, KC_K, KC_L, KC_SCLN, KC_QUOT, KC_LSFT, KC_Z, KC_X, KC_C, KC_V, KC_B, KC_N, KC_M, KC_COMM, KC_DOT, KC_SLSH, KC_RSFT, KC_BRID, KC_BRIU, KC_VOLD, KC_VOLU, KC_LCTL, TT(1), KC_ENT, TT(2), OSM(MOD_HYPR), KC_BSPC, KC_SPC, OSM(MOD_MEH), TT(3), KC_LGUI, KC_LALT, KC_ESC),
	[1] = LAYOUT_5x6(KC_F12, KC_F1, KC_F2, KC_F3, KC_F4, KC_F5, KC_F6, KC_F7, KC_F8, KC_F9, KC_F10, KC_F11, KC_TRNS, KC_NO, KC_LPRN, KC_RPRN, KC_NO, KC_NO, KC_LBRC, KC_7, KC_8, KC_9, KC_GRV, KC_INS, KC_TRNS, KC_PLUS, KC_LCBR, KC_RCBR, KC_NO, KC_NO, KC_RBRC, KC_4, KC_5, KC_6, KC_MINS, KC_PIPE, KC_LSFT, KC_TRNS, KC_NO, KC_NO, KC_TRNS, KC_TRNS, KC_0, KC_1, KC_2, KC_3, KC_EQL, KC_UNDS, KC_TRNS, KC_PSCR, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS),
	[2] = LAYOUT_5x6(RGB_TOG, RGB_RMOD, RGB_MOD, RGB_SPD, RGB_SPI, VLK_TOG, RGB_VAD, RGB_VAI, RGB_HUD, RGB_HUI, RGB_SAD, RGB_SAI, KC_TAB, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_PGUP, KC_UP, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_LSFT, KC_LALT, KC_LGUI, KC_RCTL, KC_HOME, KC_LEFT, KC_DOWN, KC_RGHT, KC_END, KC_NO, KC_NO, KC_Z, KC_X, KC_C, KC_V, KC_NO, KC_NO, KC_NO, KC_PGDN, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_ENT, KC_TRNS, KC_NO, KC_BSPC, KC_SPC, KC_DEL, KC_TRNS, KC_LGUI, KC_LALT, KC_NO),
	[3] = LAYOUT_5x6(MO(4), KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_WH_U, KC_NO, KC_NO, KC_NO, KC_NO, KC_MS_U, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_WH_L, KC_WH_D, KC_WH_R, KC_NO, KC_NO, KC_MS_L, KC_MS_D, KC_MS_R, KC_NO, KC_NO, KC_NO, KC_NO, KC_ACL0, KC_ACL1, KC_ACL2, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_BTN2, KC_NO, KC_NO, KC_NO, KC_BTN1, KC_NO, KC_TRNS, KC_NO, KC_NO, KC_NO),
	[4] = LAYOUT_5x6(KC_TRNS, KC_NO, KC_NO, KC_NO, KC_NO, RESET, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, EEP_RST, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_TRNS, KC_NO, KC_NO, KC_NO)
};

bool led_enabled_by_layer;
uint8_t previous_animation;

void keyboard_post_init_user(void) {
  // Call the post init code.
  rgblight_enable_noeeprom(); // enables Rgb, without saving settings
  previous_animation = RGBLIGHT_MODE_SNAKE;
  led_enabled_by_layer = false;
  rgblight_sethsv_noeeprom(HSV_MAGENTA);
  rgblight_mode_noeeprom(RGBLIGHT_MODE_SNAKE);
}


layer_state_t layer_state_set_user(layer_state_t state) {
  switch (get_highest_layer(state)) {
      case 4:   // reset
          if(!rgblight_is_enabled()){
            rgblight_toggle_noeeprom();
            led_enabled_by_layer = true;
          }
          rgblight_sethsv_noeeprom(HSV_RED);
          previous_animation = rgblight_get_mode();
          rgblight_mode_noeeprom(RGBLIGHT_MODE_BREATHING + 3);
          break;
      case 3:   // mouse
          if(!rgblight_is_enabled()){
            rgblight_toggle_noeeprom();
            previous_animation = rgblight_get_mode();
            rgblight_mode_noeeprom(RGBLIGHT_MODE_STATIC_LIGHT);
            led_enabled_by_layer = true;
          }
          rgblight_sethsv_noeeprom(HSV_BLUE);
          break;
      case 2:   // nav
          if(!rgblight_is_enabled()){
            rgblight_toggle_noeeprom();
            previous_animation = rgblight_get_mode();
            rgblight_mode_noeeprom(RGBLIGHT_MODE_STATIC_LIGHT);
            led_enabled_by_layer = true;
          }
          rgblight_sethsv_noeeprom(HSV_ORANGE);
          break;
      case 1:   // symbols
          if(!rgblight_is_enabled()){
            rgblight_toggle_noeeprom();
            previous_animation = rgblight_get_mode();
            rgblight_mode_noeeprom(RGBLIGHT_MODE_STATIC_LIGHT);
            led_enabled_by_layer = true;
          }
          rgblight_sethsv_noeeprom(HSV_PURPLE);
          break;
      default: //  for any other layers, or the default layer
          if(rgblight_is_enabled() && led_enabled_by_layer){
            rgblight_mode_noeeprom(previous_animation);
            rgblight_sethsv_noeeprom(HSV_MAGENTA);
            rgblight_toggle_noeeprom();
            led_enabled_by_layer = false;
          }
          else{
          	rgblight_mode_noeeprom(previous_animation);
          	rgblight_sethsv_noeeprom(HSV_MAGENTA);
          }
          break;
  }
  return state;
}


bool process_record_user(uint16_t keycode, keyrecord_t *record) {
  switch (keycode) {
    case RGB_TOG:
      if (record->event.pressed) {
      	if(led_enabled_by_layer){
      		rgblight_disable_noeeprom();
      		led_enabled_by_layer = false;
      	}
      	else{
        	rgblight_toggle_noeeprom();
    	}
      }
      return false; // Skip all further processing of this key

    case RGB_MODE_FORWARD:
      if (record->event.pressed) {
        rgblight_step_noeeprom();
      }
      return false; // Skip all further processing of this key

    case RGB_MODE_REVERSE:
      if (record->event.pressed) {
        rgblight_step_reverse_noeeprom();
      }
      return false; // Skip all further processing of this key

    case RGB_HUI:
      if (record->event.pressed) {
        rgblight_increase_hue_noeeprom();
      }
      return false; // Skip all further processing of this key

    case RGB_HUD:
      if (record->event.pressed) {
        rgblight_decrease_hue_noeeprom();
      }
      return false; // Skip all further processing of this key

    case RGB_SAI:
      if (record->event.pressed) {
        rgblight_increase_sat_noeeprom();
      }
      return false; // Skip all further processing of this key

    case RGB_SAD:
      if (record->event.pressed) {
        rgblight_decrease_sat_noeeprom();
      }
      return false; // Skip all further processing of this key

    case RGB_VAI:
      if (record->event.pressed) {
        rgblight_increase_val_noeeprom();
      }
      return false; // Skip all further processing of this key

    case RGB_VAD:
      if (record->event.pressed) {
        rgblight_decrease_val_noeeprom();
      }
      return false; // Skip all further processing of this key

    default:
      return true; // Process all other keycodes normally
  }
}